name: eduninjav2
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  bonfire: ^2.10.9
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.2.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.5.4
  image_picker: ^0.8.6
  percent_indicator: ^4.0.1
  shared_preferences: ^2.0.15
  socket_io_client: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/tile/
    - assets/images/heroes/
    - assets/images/emotes/
    - assets/images/tile/tileset/
  fonts:
    - family: Mali
      fonts:
        - asset: assets/fonts/Mali-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Mali-Light.ttf
          weight: 300
        - asset: assets/fonts/Mali-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mali-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mali-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mali-Bold.ttf
          weight: 700
